print("Hello User")
input("Login/ Register")
print("Can't find the account")
userName = input("Create new account here")
input ("Password")
input ("Confirm Password")
print("Hello user", userName)
print("Seems like this is the first time you login in the system")
print("May we ask you some question")
gender = input("Male/Female")
age = input ("How old are you")
location = input("Where do you live")
print("So you are", "\033[31m",userName,"\033[32m",age,"\033[34m","live in/at",location )
