print("Getting to know you!")
print()
name = input("What's your name? ")
food = input("What's your favorite food? ")
music = input("What's your favorite music? ")
state = input("Where do you live? ")
print()
print("You are")
print(name)
print("You're probably hungry for")
print(food)
print("and you're definitely getting your groove on to")
print(music)
print("living in the amazing")
print(state)
